/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("libs")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    // testImplementation(libs.junit.jupiter)

    // testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // implementation(files("libs/text-table-formatter-1.1.2.jar")) 

    // https://mvnrepository.com/artifact/org.nocrala.tools.texttablefmt/text-table-formatter
    implementation("org.nocrala.tools.texttablefmt:text-table-formatter:1.2.4")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "kbgteamapp.App"
}

tasks.jar {
    archiveBaseName.set("KBGTeamApp")
    archiveVersion.set("1.1.0")
    manifest {
        attributes["Main-Class"] = "kbgteamapp.App"
    }
    from(sourceSets.main.get().output)

    // Include dependencies in the JAR
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}


// tasks.named<Test>("test") {
//     // Use JUnit Platform for unit tests.
//     useJUnitPlatform()
// }
